source "https://rubygems.org"

gem "roda", "~> 2.15"
gem "tilt"
gem "rack_csrf"

gem "sequel"
gem "sqlite3"

gem "shrine", "~> 2.7"
gem "shrine-transloadit", path: ".."
gem "shrine-url"
gem "aws-sdk-s3", "~> 1.2"
gem "dotenv"

gem "sucker_punch", "~> 2.0"

gem "pry-byebug"
