source "https://rubygems.org"

gem "roda", "~> 3.10"
gem "forme"
gem "tilt"
gem "erubi"
gem "puma"

gem "sequel", "~> 5.0"
gem "sqlite3"

gem "shrine", ">= 3.0.0.beta2"
gem "shrine-transloadit", path: ".."
gem "shrine-url", "~> 2.2"
gem "aws-sdk-s3", "~> 1.14"
gem "dry-monitor"
gem "dotenv"

gem "sucker_punch", "~> 2.0"

gem "pry"
